version = 0.1
[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "delay-authentication-staging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1js61lddvzyha"
s3_prefix = "delay-authentication-staging"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"staging\""
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "delay-authentication-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1js61lddvzyha"
s3_prefix = "delay-authentication-prod"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"prod\""
image_repositories = []
