AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: delay-authentication

Globals:
  Function:
    Timeout: 5
    Runtime: python3.9
    Architecture: [ x86_64 ]
    Layers: [ !Ref DependenciesLayer ]
    Environment:
      Variables:
        StageName: !Ref StageName
        UserPoolArn: !Ref UserPoolArn

Parameters:
  StageName:
    Type: String
    Default: default
  AuthArn:
    Type: String
    Default: default

Resources:

  AuthenticationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      TracingEnabled: true
      DefinitionBody:
        Fn::Transform:
          Name: AWS:Include
          Parameters:
            Location: openapi.yaml
      Auth:
        DefaultAuthorizer: DelaygramAuthorizer
        Authorizer:
          DelaygramAuthorizer:
            UserPoolArn:
              Fn::Sub: arn:aws:cognito-idp:eu-west-3:088217417350:userpool/eu-west-3_${AuthArn}

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: !GetAtt Dependencies.zip
      CompatibleRuntimes: [ python3.9 ]
      LayerName: !Ref DependenciesLayerName
      LicenseInfo: !Ref DependenciesLicense

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
